"""baseline version 8 schema

Revision ID: 12799efbfd56
Revises: d4b1a2c3e4f5
Create Date: 2026-08-03 15:35:04.027262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "12799efbfd56"
down_revision: Union[str, Sequence[str], None] = "d4b1a2c3e4f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_table_if_missing(name: str, *columns, **kwargs) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table(name):
        return

    op.create_table(name, *columns, **kwargs)


def _create_index_if_missing(
    name: str,
    table_name: str,
    columns,
    *,
    unique: bool = False,
    **kwargs,
) -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table(table_name):
        return

    existing = {
        index.get("name")
        for index in inspector.get_indexes(table_name)
    }

    if name in existing:
        return

    op.create_index(
        name,
        table_name,
        columns,
        unique=unique,
        **kwargs,
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _create_table_if_missing('automation_job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(length=80), nullable=False),
    sa.Column('job_name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_automation_job_runs_id'), 'automation_job_runs', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_automation_job_runs_job_id'), 'automation_job_runs', ['job_id'], unique=False)
    _create_index_if_missing(op.f('ix_automation_job_runs_status'), 'automation_job_runs', ['status'], unique=False)
    _create_table_if_missing('capture_iteration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_root', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('matches_captured', sa.Integer(), nullable=False),
    sa.Column('bytes_written', sa.Integer(), nullable=False),
    sa.Column('captures_waiting', sa.Integer(), nullable=False),
    sa.Column('retries_attempted', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_capture_iteration_history_capture_root'), 'capture_iteration_history', ['capture_root'], unique=False)
    _create_index_if_missing(op.f('ix_capture_iteration_history_id'), 'capture_iteration_history', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_capture_iteration_history_match_id'), 'capture_iteration_history', ['match_id'], unique=False)
    _create_index_if_missing(op.f('ix_capture_iteration_history_provider'), 'capture_iteration_history', ['provider'], unique=False)
    _create_index_if_missing(op.f('ix_capture_iteration_history_status'), 'capture_iteration_history', ['status'], unique=False)
    _create_table_if_missing('data_provenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_data_provenance_entity_type'), 'data_provenance', ['entity_type'], unique=False)
    _create_index_if_missing(op.f('ix_data_provenance_internal_id'), 'data_provenance', ['internal_id'], unique=False)
    _create_table_if_missing('feed_connector_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('connector_type', sa.String(length=30), nullable=False),
    sa.Column('feed_url', sa.Text(), nullable=True),
    sa.Column('auth_token', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('competitions_json', sa.Text(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('refresh_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_feed_connector_configs_connector_id'), 'feed_connector_configs', ['connector_id'], unique=True)
    _create_table_if_missing('feed_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_new', sa.Integer(), nullable=False),
    sa.Column('records_existing', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_feed_sync_runs_connector_id'), 'feed_sync_runs', ['connector_id'], unique=False)
    _create_table_if_missing('historical_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('competition_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('received_rows', sa.Integer(), nullable=False),
    sa.Column('created_matches', sa.Integer(), nullable=False),
    sa.Column('duplicate_matches', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('created_players', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rolled_back_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_historical_import_batches_batch_uuid'), 'historical_import_batches', ['batch_uuid'], unique=True)
    _create_index_if_missing(op.f('ix_historical_import_batches_competition_code'), 'historical_import_batches', ['competition_code'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_batches_provider'), 'historical_import_batches', ['provider'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_batches_status'), 'historical_import_batches', ['status'], unique=False)
    _create_table_if_missing('intelligence_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_intelligence_profiles_id'), 'intelligence_profiles', ['id'], unique=False)
    _create_table_if_missing('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('tournament', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('match_format', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('player_a', sa.String(), nullable=True),
    sa.Column('player_b', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('first_180_player', sa.String(), nullable=True),
    sa.Column('first_leg_winner', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    _create_table_if_missing('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_date', sa.Date(), nullable=False),
    sa.Column('tournament', sa.String(), nullable=True),
    sa.Column('player_a', sa.String(), nullable=False),
    sa.Column('player_b', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint', name='uq_odds_snapshot_fingerprint')
    )
    _create_index_if_missing(op.f('ix_odds_snapshots_bookmaker'), 'odds_snapshots', ['bookmaker'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_captured_at'), 'odds_snapshots', ['captured_at'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_fixture_date'), 'odds_snapshots', ['fixture_date'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_id'), 'odds_snapshots', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_market'), 'odds_snapshots', ['market'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_player_a'), 'odds_snapshots', ['player_a'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_player_b'), 'odds_snapshots', ['player_b'], unique=False)
    _create_index_if_missing(op.f('ix_odds_snapshots_selection'), 'odds_snapshots', ['selection'], unique=False)
    _create_table_if_missing('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('checkout', sa.Float(), nullable=True),
    sa.Column('one80_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_players_id'), 'players', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_players_name'), 'players', ['name'], unique=True)
    _create_table_if_missing('prediction_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_uuid', sa.String(length=36), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('tournament', sa.String(length=200), nullable=True),
    sa.Column('player_a', sa.String(length=200), nullable=False),
    sa.Column('player_b', sa.String(length=200), nullable=False),
    sa.Column('official_selection', sa.String(length=200), nullable=False),
    sa.Column('official_probability', sa.Float(), nullable=False),
    sa.Column('legacy_probability_a', sa.Float(), nullable=False),
    sa.Column('intelligence_probability_a', sa.Float(), nullable=True),
    sa.Column('prediction_confidence', sa.String(length=30), nullable=True),
    sa.Column('explanation_confidence', sa.String(length=30), nullable=True),
    sa.Column('profile_name', sa.String(length=120), nullable=True),
    sa.Column('profile_version', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('application_version', sa.String(length=50), nullable=False),
    sa.Column('shadow_mode', sa.Boolean(), nullable=False),
    sa.Column('intelligence_rating_a', sa.Float(), nullable=True),
    sa.Column('intelligence_rating_b', sa.Float(), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_prediction_audits_audit_uuid'), 'prediction_audits', ['audit_uuid'], unique=True)
    _create_index_if_missing(op.f('ix_prediction_audits_created_at'), 'prediction_audits', ['created_at'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_id'), 'prediction_audits', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_official_selection'), 'prediction_audits', ['official_selection'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_player_a'), 'prediction_audits', ['player_a'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_player_b'), 'prediction_audits', ['player_b'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_prediction_id'), 'prediction_audits', ['prediction_id'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_profile_name'), 'prediction_audits', ['profile_name'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audits_tournament'), 'prediction_audits', ['tournament'], unique=False)
    _create_table_if_missing('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('player_a', sa.String(), nullable=True),
    sa.Column('player_b', sa.String(), nullable=True),
    sa.Column('predicted_winner', sa.String(), nullable=True),
    sa.Column('win_prob_a', sa.Float(), nullable=True),
    sa.Column('win_prob_b', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('rating_a', sa.Float(), nullable=True),
    sa.Column('rating_b', sa.Float(), nullable=True),
    sa.Column('first_180_a', sa.Float(), nullable=True),
    sa.Column('first_180_b', sa.Float(), nullable=True),
    sa.Column('actual_winner', sa.String(), nullable=True),
    sa.Column('actual_first_180_player', sa.String(), nullable=True),
    sa.Column('winner_correct', sa.Integer(), nullable=True),
    sa.Column('first_180_correct', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    _create_table_if_missing('provider_entity_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=False),
    sa.Column('competition_code', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'entity_type', 'external_id', name='uq_provider_entity')
    )
    _create_index_if_missing(op.f('ix_provider_entity_mappings_competition_code'), 'provider_entity_mappings', ['competition_code'], unique=False)
    _create_index_if_missing(op.f('ix_provider_entity_mappings_entity_type'), 'provider_entity_mappings', ['entity_type'], unique=False)
    _create_index_if_missing(op.f('ix_provider_entity_mappings_internal_id'), 'provider_entity_mappings', ['internal_id'], unique=False)
    _create_index_if_missing(op.f('ix_provider_entity_mappings_provider'), 'provider_entity_mappings', ['provider'], unique=False)
    _create_table_if_missing('provider_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_accepted', sa.Integer(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_provider_sync_runs_id'), 'provider_sync_runs', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_provider_sync_runs_operation'), 'provider_sync_runs', ['operation'], unique=False)
    _create_index_if_missing(op.f('ix_provider_sync_runs_provider_id'), 'provider_sync_runs', ['provider_id'], unique=False)
    _create_index_if_missing(op.f('ix_provider_sync_runs_status'), 'provider_sync_runs', ['status'], unique=False)
    _create_table_if_missing('raw_ingestion_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'entity_type', 'external_id', 'checksum', name='uq_raw_source_version')
    )
    _create_index_if_missing(op.f('ix_raw_ingestion_records_checksum'), 'raw_ingestion_records', ['checksum'], unique=False)
    _create_index_if_missing(op.f('ix_raw_ingestion_records_entity_type'), 'raw_ingestion_records', ['entity_type'], unique=False)
    _create_index_if_missing(op.f('ix_raw_ingestion_records_provider'), 'raw_ingestion_records', ['provider'], unique=False)
    _create_table_if_missing('strategy_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('strategy_uuid', sa.String(length=36), nullable=False),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('enforcement_mode', sa.String(length=20), nullable=False),
    sa.Column('trading_mode', sa.String(length=20), nullable=False),
    sa.Column('competition', sa.String(length=200), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('bookmaker', sa.String(length=120), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('confidence_percent', sa.Float(), nullable=False),
    sa.Column('decimal_odds', sa.Float(), nullable=False),
    sa.Column('edge_percent', sa.Float(), nullable=False),
    sa.Column('expected_value_percent', sa.Float(), nullable=False),
    sa.Column('official_decision', sa.String(length=30), nullable=False),
    sa.Column('official_stake', sa.Float(), nullable=False),
    sa.Column('strategy_decision', sa.String(length=30), nullable=False),
    sa.Column('strategy_stake', sa.Float(), nullable=False),
    sa.Column('effective_decision', sa.String(length=30), nullable=False),
    sa.Column('effective_stake', sa.Float(), nullable=False),
    sa.Column('blockers_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_strategy_decisions_competition'), 'strategy_decisions', ['competition'], unique=False)
    _create_index_if_missing(op.f('ix_strategy_decisions_created_at'), 'strategy_decisions', ['created_at'], unique=False)
    _create_index_if_missing(op.f('ix_strategy_decisions_decision_uuid'), 'strategy_decisions', ['decision_uuid'], unique=True)
    _create_index_if_missing(op.f('ix_strategy_decisions_id'), 'strategy_decisions', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_strategy_decisions_market'), 'strategy_decisions', ['market'], unique=False)
    _create_index_if_missing(op.f('ix_strategy_decisions_strategy_name'), 'strategy_decisions', ['strategy_name'], unique=False)
    _create_index_if_missing(op.f('ix_strategy_decisions_strategy_uuid'), 'strategy_decisions', ['strategy_uuid'], unique=False)
    _create_table_if_missing('strategy_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_uuid', 'version', name='uq_strategy_uuid_version')
    )
    _create_index_if_missing(op.f('ix_strategy_profiles_id'), 'strategy_profiles', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_strategy_profiles_strategy_uuid'), 'strategy_profiles', ['strategy_uuid'], unique=False)
    _create_table_if_missing('bet_slip_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=False),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('kelly_stake', sa.Float(), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['fixture_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixture_id', 'market', 'selection', name='uq_bet_slip_fixture_market_selection')
    )
    _create_index_if_missing(op.f('ix_bet_slip_items_fixture_id'), 'bet_slip_items', ['fixture_id'], unique=False)
    _create_index_if_missing(op.f('ix_bet_slip_items_id'), 'bet_slip_items', ['id'], unique=False)
    _create_table_if_missing('historical_import_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=24), nullable=False),
    sa.Column('internal_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('created_by_batch', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['historical_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_historical_import_items_action'), 'historical_import_items', ['action'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_items_batch_id'), 'historical_import_items', ['batch_id'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_items_entity_type'), 'historical_import_items', ['entity_type'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_items_internal_id'), 'historical_import_items', ['internal_id'], unique=False)
    _create_table_if_missing('historical_import_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preview_uuid', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('competition_code', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('rows_json', sa.Text(), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['historical_import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_historical_import_previews_batch_id'), 'historical_import_previews', ['batch_id'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_previews_competition_code'), 'historical_import_previews', ['competition_code'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_previews_preview_uuid'), 'historical_import_previews', ['preview_uuid'], unique=True)
    _create_index_if_missing(op.f('ix_historical_import_previews_provider'), 'historical_import_previews', ['provider'], unique=False)
    _create_index_if_missing(op.f('ix_historical_import_previews_status'), 'historical_import_previews', ['status'], unique=False)
    _create_table_if_missing('match_player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('one80s', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('checkout', sa.Float(), nullable=True),
    sa.Column('first9_average', sa.Float(), nullable=True),
    sa.Column('highest_checkout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('bookmaker', sa.String(), nullable=True),
    sa.Column('odds', sa.Float(), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_paper_trades_id'), 'paper_trades', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_paper_trades_prediction_id'), 'paper_trades', ['prediction_id'], unique=False)
    _create_table_if_missing('player_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=180), nullable=False),
    sa.Column('alias_key', sa.String(length=180), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_player_aliases_alias_key'), 'player_aliases', ['alias_key'], unique=False)
    _create_index_if_missing(op.f('ix_player_aliases_player_id'), 'player_aliases', ['player_id'], unique=False)
    _create_index_if_missing(op.f('ix_player_aliases_provider'), 'player_aliases', ['provider'], unique=False)
    _create_table_if_missing('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('matches', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('legs_won', sa.Integer(), nullable=True),
    sa.Column('legs_lost', sa.Integer(), nullable=True),
    sa.Column('first9_average', sa.Float(), nullable=True),
    sa.Column('one80_total', sa.Integer(), nullable=True),
    sa.Column('one80_per_match', sa.Float(), nullable=True),
    sa.Column('checkout100', sa.Integer(), nullable=True),
    sa.Column('highest_checkout', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_table_if_missing('prediction_audit_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('actual_winner', sa.String(length=200), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['prediction_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index_if_missing(op.f('ix_prediction_audit_outcomes_audit_id'), 'prediction_audit_outcomes', ['audit_id'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audit_outcomes_id'), 'prediction_audit_outcomes', ['id'], unique=False)
    _create_index_if_missing(op.f('ix_prediction_audit_outcomes_recorded_at'), 'prediction_audit_outcomes', ['recorded_at'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """
    Keep the catch-up baseline intentionally irreversible.

    This revision may adopt tables that existed before Alembic tracked
    them, so dropping them during downgrade could destroy real data.
    """
    pass
